name: ai_primer
channels:
  - https://repo.anaconda.com/pkgs/free
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _anaconda_depends=2019.03
  - _libgcc_mutex=0.1
  - alabaster=0.7.12
  - anaconda=custom
  - anaconda-client=1.7.2
  - anaconda-project=0.8.3
  - asn1crypto=0.24.0
  - astroid=2.2.5
  - astropy=3.2.1
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - babel=2.7.0
  - backcall=0.1.0
  - backports=1.0
  - backports.os=0.1.1
  - backports.shutil_get_terminal_size=1.0.0
  - beautifulsoup4=4.8.0
  - binutils_impl_linux-64=2.31.1
  - binutils_linux-64=2.31.1
  - bitarray=1.0.1
  - bkcharts=0.2
  - blas=1.0
  - bleach=3.1.0
  - blosc=1.15.0
  - bokeh=1.3.4
  - boost-cpp=1.67.0
  - boto=2.49.0
  - bottleneck=1.2.1
  - bzip2=1.0.6
  - ca-certificates=2019.5.15
  - cairo=1.14.12
  - certifi=2019.6.16
  - cffi=1.12.3
  - chardet=3.0.4
  - click=7.0
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cloudpickle=1.2.1
  - clyent=1.2.2
  - colorama=0.4.1
  - colorlover=0.3.0
  - contextlib2=0.5.5
  - cryptography=2.7
  - cufflinks-py=0.13.0
  - curl=7.64.0
  - cycler=0.10.0
  - cython=0.29.13
  - cytoolz=0.10.0
  - dask=2.3.0
  - dask-core=2.3.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.6.0
  - descartes=1.1.0
  - distributed=2.3.2
  - docutils=0.15.2
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.2.6
  - fastcache=1.1.0
  - filelock=3.0.12
  - fiona=1.8.4
  - flask=1.1.1
  - fontconfig=2.13.0
  - freetype=2.9.1
  - freexl=1.0.5
  - fribidi=1.0.5
  - fsspec=0.4.0
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gdal=2.3.3
  - geopandas=0.4.1
  - geos=3.7.1
  - get_terminal_size=1.0.0
  - gevent=1.4.0
  - giflib=5.1.9
  - glib=2.56.2
  - glob2=0.7
  - gmp=6.1.2
  - gmpy2=2.0.8
  - graphite2=1.3.13
  - greenlet=0.4.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - h5py=2.9.0
  - harfbuzz=1.8.8
  - hdf4=4.2.13
  - hdf5=1.10.4
  - heapdict=1.0.0
  - html5lib=1.0.1
  - icu=58.2
  - idna=2.8
  - imageio=2.5.0
  - imagesize=1.1.0
  - importlib_metadata=0.19
  - intel-openmp=2019.3
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - itsdangerous=1.1.0
  - jbig=2.1
  - jdcal=1.4.1
  - jedi=0.15.1
  - jeepney=0.4
  - jinja2=2.10.1
  - joblib=0.13.2
  - jpeg=9b
  - json-c=0.13.1
  - json5=0.8.5
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=5.3.1
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - jupyterlab=1.0.2
  - jupyterlab_server=1.0.0
  - kealib=1.4.10
  - keyring=18.0.0
  - kiwisolver=1.1.0
  - krb5=1.16.1
  - lazy-object-proxy=1.4.2
  - libarchive=3.3.3
  - libboost=1.67.0
  - libcurl=7.64.0
  - libdap4=3.19.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgdal=2.3.3
  - libgfortran-ng=7.3.0
  - libgpuarray=0.7.6
  - libkml=1.3.0
  - liblief=0.9.0
  - libnetcdf=4.6.1
  - libpng=1.6.36
  - libpq=11.2
  - libsodium=1.0.16
  - libspatialindex=1.9.0
  - libspatialite=4.3.0a
  - libssh2=1.8.0
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.10
  - libtool=2.4.6
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - libxslt=1.1.33
  - llvmlite=0.29.0
  - locket=0.2.0
  - lxml=4.4.1
  - lz4-c=1.8.1.2
  - lzo=2.10
  - mako=1.1.0
  - mapclassify=2.0.1
  - markupsafe=1.1.1
  - matplotlib=3.0.3
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.3
  - mkl-service=2.0.2
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - more-itertools=7.2.0
  - mpc=1.1.0
  - mpfr=4.0.1
  - mpmath=1.1.0
  - msgpack-python=0.6.1
  - multipledispatch=0.6.0
  - munch=2.3.2
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.3
  - nltk=3.4.5
  - nose=1.3.7
  - notebook=6.0.0
  - numba=0.45.1
  - numexpr=2.6.9
  - numpy=1.16.4
  - numpy-base=1.16.4
  - numpydoc=0.9.1
  - olefile=0.46
  - openjpeg=2.3.1
  - openpyxl=2.6.2
  - openssl=1.1.1d
  - packaging=19.1
  - pandas=0.25.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.5.1
  - partd=1.0.0
  - patchelf=0.9
  - path.py=12.0.1
  - pathlib2=2.3.4
  - patsy=0.5.1
  - pcre=8.43
  - pep8=1.7.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.1.0
  - pip=19.2.2
  - pixman=0.38.0
  - pkginfo=1.5.0.1
  - plotly=2.7.0
  - pluggy=0.12.0
  - ply=3.11
  - poppler=0.65.0
  - poppler-data=0.4.9
  - proj4=5.2.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - psutil=5.6.3
  - psycopg2=2.7.6.1
  - ptyprocess=0.6.0
  - py=1.8.0
  - py-lief=0.9.0
  - pycodestyle=2.5.0
  - pycosat=0.6.3
  - pycparser=2.19
  - pycrypto=2.6.1
  - pycurl=7.43.0.2
  - pyflakes=2.1.1
  - pygments=2.4.2
  - pygpu=0.7.6
  - pylint=2.3.1
  - pymc=2.3.7
  - pymc3=3.5
  - pyodbc=4.0.27
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyproj=1.9.6
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - pysocks=1.7.0
  - pytables=3.5.1
  - pytest=5.0.1
  - pytest-arraydiff=0.3
  - pytest-astropy=0.5.0
  - pytest-doctestplus=0.3.0
  - pytest-openfiles=0.3.2
  - pytest-remotedata=0.3.2
  - python=3.6.8
  - python-dateutil=2.8.0
  - python-libarchive-c=2.8
  - pytz=2019.2
  - pywavelets=1.0.3
  - pyyaml=5.1.2
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtawesome=0.5.7
  - qtconsole=4.5.4
  - qtpy=1.9.0
  - readline=7.0
  - requests=2.22.0
  - rope=0.14.0
  - rtree=0.8.3
  - ruamel_yaml=0.15.46
  - scikit-image=0.15.0
  - scikit-learn=0.21.1
  - scipy=1.2.1
  - seaborn=0.9.0
  - secretstorage=3.1.1
  - send2trash=1.5.0
  - setuptools=41.0.1
  - shapely=1.6.4
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.13
  - six=1.12.0
  - snappy=1.1.7
  - snowballstemmer=1.9.0
  - sortedcollections=1.1.2
  - sortedcontainers=2.1.0
  - soupsieve=1.9.2
  - sphinx=2.1.2
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.1
  - sphinxcontrib-devhelp=1.0.1
  - sphinxcontrib-htmlhelp=1.0.2
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.2
  - sphinxcontrib-serializinghtml=1.1.3
  - sphinxcontrib-websupport=1.1.2
  - spyder=3.3.6
  - spyder-kernels=0.5.1
  - sqlalchemy=1.3.7
  - sqlite=3.27.2
  - statsmodels=0.10.1
  - sympy=1.4
  - tbb=2019.4
  - tblib=1.4.0
  - terminado=0.8.2
  - testpath=0.4.2
  - theano=1.0.3
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.3
  - tqdm=4.32.1
  - traitlets=4.3.2
  - typed-ast=1.3.4
  - unicodecsv=0.14.1
  - unixodbc=2.3.7
  - urllib3=1.24.2
  - util-linux=2.21
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.15.5
  - wheel=0.33.4
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - wurlitzer=1.0.3
  - xerces-c=3.2.2
  - xlrd=1.2.0
  - xlsxwriter=1.1.8
  - xlwt=1.3.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zict=1.0.0
  - zipp=0.5.2
  - zlib=1.2.11
  - zstd=1.3.7
prefix: /home/trokas/anaconda3/envs/ai_primer

